### ISSUE TITLE
Washington Post - Needs an update

### ISSUE THREAD

**Issue by JonnyRedHed** [deelawn/user-scripts#1]
![washpost - copy](https://user-images.githubusercontent.com/7356491/40580963-e0518280-6143-11e8-80fd-47a21f2f7d55.PNG)
I think it needs updating. The site appears to be using new cookie and site code behaviour.

**Comment by JonnyRedHed** [comment]
Could you give the washpost a fresh look please.  There is a large verticel blue banner when you try and click through to an article whichs tops you going any further.

![washpost blue article banner - Copy](https://user-images.githubusercontent.com/7356491/58371184-19735c00-7f07-11e9-9146-943d2c2de555.png)

**Comment by deelawn** [comment]
@JonnyRedHed Try turning off your add blocker. The user script is still working for me

**Comment by JonnyRedHed** [comment]
Yeah, I'm not seeing that result when I turn Opera (stable) adblocking off and Brave (developer) and Brave (stable) browsers shields off for the website.

**Comment by JonnyRedHed** [comment]
Oh, 
Can we expect an update.

**Comment by deelawn** [comment]
No update. As it says in the README, these scripts are only supported for Firefox and Chrome

**Comment by JonnyRedHed** [comment]
Ah, I see, so not chrome based browsers.
